#!/bin/bash

cd /usr/local/bin
wget https://raw.githubusercontent.com/lachm/cmd-line-trash/master/empty-trash
wget https://raw.githubusercontent.com/lachm/cmd-line-trash/master/list-trash
wget https://raw.githubusercontent.com/lachm/cmd-line-trash/master/put-trash-back
wget https://raw.githubusercontent.com/lachm/cmd-line-trash/master/trash
