#!/bin/bash

PREFIX="[trash] "
function printwith {
	printf "$PREFIX$1\n"
}

if (( $# != 1 )); then
	printwith "Usage: trash-putback FILE"
	exit 1
fi

if [[ ! -d ~/.TrashBin ]] || [[ ! -d ~/.TrashBinInfo ]]; then
	mkdir ~/.TrashBin
	mkdir ~/.TrashBinInfo
fi

if [[ -e ~/.TrashBin/"$1" ]]; then
	if [[ -e ~/.TrashBinInfo/."$1".trashinfo ]]; then
		PUTBACK=`cat ~/.TrashBinInfo/."$1".trashinfo`
		mv ~/.TrashBin/"$1" $PUTBACK && rm ~/.TrashBinInfo/."$1".trashinfo &&
		printwith "File "$1" put back as "$PUTBACK""
	else
		mv ~/.TrashBin/"$1" ~/ &&
		printwith "Couldn't find info file" &&
		printwith "File "$1" put back into home directory"
	fi
else
	printwith "File "$1" is not in the trash"
fi
