#!/bin/bash

if (( $# < 1 )); then
	echo "Usage: trash FILE"
	exit 1
fi

PREFIX="[trash] "
function printwith {
	echo "$PREFIX$1"
}

function trashfunc {
	if [[ ! -d ~/.TrashBin ]] || [[ ! -d ~/.TrashBinInfo ]]; then
		mkdir ~/.TrashBin
		mkdir ~/.TrashBinInfo
	fi

	if [[ -e $1 ]]; then
		mv $1 ~/.TrashBin/
		BASENAME=`basename "$1"`
		DIRNAME=`dirname "$1"`
		cd "$DIRNAME"
		PWD=`pwd`
		FULLPATH="$PWD/$BASENAME"
		echo $FULLPATH > ~/.TrashBinInfo/."$BASENAME".trashinfo
		printwith "File "$1" moved to trash"
	else
		printwith "File "$1" does not exist"
	fi
}

for i in "$@"; do
	trashfunc $i
done
