#!/bin/bash

PREFIX="[trash] "
function printwith {
	printf "$PREFIX$1"
}
SUCCESSMSG="Trash emptied successfully\n"

if [[ -d ~/.TrashBin ]]; then
	rm -r ~/.TrashBin
	mkdir ~/.TrashBin
else
	mkdir ~/.TrashBin
fi

if [[ -d ~/.TrashBinInfo ]]; then
	rm -r ~/.TrashBinInfo
	mkdir ~/.TrashBinInfo
else
	mkdir ~/.TrashBinInfo
fi

printwith "$SUCCESSMSG"
