#!/bin/bash

PREFIX="[trash] "
function printwith {
    printf "$PREFIX$1"
}
EMPTYMSG="Trash is empty\n"

if [[ ! -d ~/.TrashBinInfo ]]; then mkdir ~/.TrashBinInfo; fi

if [[ -d ~/.TrashBin  ]]; then
  cd ~/.TrashBin
  if [[ `ls -A` == "" ]]; then
    printwith "$EMPTYMSG"
  else
    ls -A
  fi
else
  mkdir ~/.TrashBin
  printwith "$EMPTYMSG"
fi
